### ISSUE TITLE
Cant compile on Ubuntu 16.10

### ISSUE THREAD

**Issue by TheServer201** [alexjbest/ajs#30]
```x@x-VirtualBox:~/ajs$ make
g++ -c -I. -I/home/x/asmjit/src/ -I/home/x/sources/gmp-6.1.1/ -I/home/x/build/gmp-6.1.1/ -o line.o line.cpp -g -O2 --std=c++0x -Wall
In file included from line.cpp:2:0:
line.h:32:26: error: ‘kInstIdNone’ is not a member of ‘asmjit’
     Line(uint32_t inst = asmjit::kInstIdNone):
                          ^~~~~~
line.h: In constructor ‘Line::Line(uint32_t)’:
line.h:34:14: error: ‘noOperand’ is not a member of ‘asmjit’
         ops({asmjit::noOperand, asmjit::noOperand, asmjit::noOperand}),
              ^~~~~~
line.h:34:33: error: ‘noOperand’ is not a member of ‘asmjit’
         ops({asmjit::noOperand, asmjit::noOperand, asmjit::noOperand}),
                                 ^~~~~~
line.h:34:52: error: ‘noOperand’ is not a member of ‘asmjit’
         ops({asmjit::noOperand, asmjit::noOperand, asmjit::noOperand}),
                                                    ^~~~~~
line.h:41:46: error: invalid initializer for array member ‘asmjit::Operand Line::ops [4]’
         regsOut(std::vector<asmjit::X86Reg>()) {
                                              ^
line.cpp: In member function ‘int Line::isInstruction() const’:
line.cpp:59:25: error: ‘kInstIdNone’ is not a member of ‘asmjit’
   return instruction != asmjit::kInstIdNone;
                         ^~~~~~
line.cpp: In member function ‘int Line::isLabel() const’:
line.cpp:63:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   return label != -1;
          ~~~~~~^~~~~
line.cpp: In member function ‘void Line::setLabel(uint32_t)’:
line.cpp:94:17: error: ‘kInstIdNone’ is not a member of ‘asmjit’
   instruction = asmjit::kInstIdNone;
                 ^~~~~~
line.cpp: In member function ‘void Line::setAlign(uint8_t)’:
line.cpp:101:17: error: ‘kInstIdNone’ is not a member of ‘asmjit’
   instruction = asmjit::kInstIdNone;
                 ^~~~~~
line.cpp: In member function ‘void Line::setByte(uint8_t)’:
line.cpp:108:17: error: ‘kInstIdNone’ is not a member of ‘asmjit’
   instruction = asmjit::kInstIdNone;
                 ^~~~~~
line.cpp: In member function ‘void Line::addRegIn(asmjit::X86Reg)’:
line.cpp:122:11: error: ‘X86GpReg’ is not a member of ‘asmjit’
     reg = asmjit::X86GpReg(asmjit::kX86RegTypeGpq, reg.getRegIndex(), 8);
           ^~~~~~
line.cpp:122:28: error: ‘kX86RegTypeGpq’ is not a member of ‘asmjit’
     reg = asmjit::X86GpReg(asmjit::kX86RegTypeGpq, reg.getRegIndex(), 8);
                            ^~~~~~
line.cpp:122:56: error: ‘class asmjit::X86Reg’ has no member named ‘getRegIndex’
     reg = asmjit::X86GpReg(asmjit::kX86RegTypeGpq, reg.getRegIndex(), 8);
                                                        ^~~~~~~~~~~
line.cpp:125:11: error: ‘X86ZmmReg’ is not a member of ‘asmjit’
     reg = asmjit::X86ZmmReg(asmjit::kX86RegTypeZmm, reg.getRegIndex(), 64);
           ^~~~~~
line.cpp:125:29: error: ‘kX86RegTypeZmm’ is not a member of ‘asmjit’
     reg = asmjit::X86ZmmReg(asmjit::kX86RegTypeZmm, reg.getRegIndex(), 64);
                             ^~~~~~
line.cpp:125:57: error: ‘class asmjit::X86Reg’ has no member named ‘getRegIndex’
     reg = asmjit::X86ZmmReg(asmjit::kX86RegTypeZmm, reg.getRegIndex(), 64);
                                                         ^~~~~~~~~~~
line.cpp: In member function ‘void Line::addRegOut(asmjit::X86Reg)’:
line.cpp:132:11: error: ‘X86GpReg’ is not a member of ‘asmjit’
     reg = asmjit::X86GpReg(asmjit::kX86RegTypeGpq, reg.getRegIndex(), 8);
           ^~~~~~
line.cpp:132:28: error: ‘kX86RegTypeGpq’ is not a member of ‘asmjit’
     reg = asmjit::X86GpReg(asmjit::kX86RegTypeGpq, reg.getRegIndex(), 8);
                            ^~~~~~
line.cpp:132:56: error: ‘class asmjit::X86Reg’ has no member named ‘getRegIndex’
     reg = asmjit::X86GpReg(asmjit::kX86RegTypeGpq, reg.getRegIndex(), 8);
                                                        ^~~~~~~~~~~
line.cpp:135:11: error: ‘X86ZmmReg’ is not a member of ‘asmjit’
     reg = asmjit::X86ZmmReg(asmjit::kX86RegTypeZmm, reg.getRegIndex(), 64);
           ^~~~~~
line.cpp:135:29: error: ‘kX86RegTypeZmm’ is not a member of ‘asmjit’
     reg = asmjit::X86ZmmReg(asmjit::kX86RegTypeZmm, reg.getRegIndex(), 64);
                             ^~~~~~
line.cpp:135:57: error: ‘class asmjit::X86Reg’ has no member named ‘getRegIndex’
     reg = asmjit::X86ZmmReg(asmjit::kX86RegTypeZmm, reg.getRegIndex(), 64);
                                                         ^~~~~~~~~~~
Makefile:44: recipe for target 'line.o' failed
make: *** [line.o] Error 1
```

**Comment by alexjbest** [comment]
Hi, apologies, I haven't worked on ajs for a little while, the most recent work was done by @akruppa and I was periodically pulling from him but not up to date, which could be causing your issue.

We are still using a patched version of asmjit, located at alexjbest/asmjit as we had need of a few extra hacked in features, if you aren't already you will need to (re-)pull from there in order to build ajs. I have updated the README to make this more clear. Indeed it looks like there have been a lot of changes to the master asmjit which we haven't kept up with, which is another possible cause of your problems.

Thanks for letting me know, if you're still having issues update me and I'll see what I can do.

**Comment by TheServer201** [comment]
Thanx for the fast answer but I already tried the most recent asmjit and the one on your github and any of them have the needed nembers.

**Comment by wbhart** [comment]
The latest version of ajs is here:

https://github.com/akruppa/ajs

The assembly superoptimiser is provided as is. It was custom written for
superoptimising MPIR and requires specialised kernel customisations to make
it work in practice. Of course, we'd absolutely love someone to take over
maintenance of the project now that the grant funding has run out, but it
still requires a large amount of human intervention to make it work on any
given system.

Please note that alexjbest and akruppa are not expected to continue
maintenance of the superoptimiser itself.

**Comment by alexjbest** [comment]
The two ajs repositories should be pretty much even right now.
In any case the members are defined, in the alexjbest/asmjit repo (certainly the most recent asmjit won't work), eg. at:
https://github.com/alexjbest/asmjit/blob/master/src/asmjit/base/assembler.h#L34
https://github.com/alexjbest/asmjit/blob/master/src/asmjit/base/operand.h#L630
I guess you have to check that everything is getting included right, the Makefile has changed since I was working on the project but FWIW with both the patched old asmjit and this repo at master it currently compiles for me.

**Comment by TheServer201** [comment]
Sorry for the late reply. I think I will write my own superoptimiser based on your since your projet is not expected to continue.
